### ISSUE TITLE
id_token cannot always be parsed. 

### ISSUE THREAD

**Issue by appie2go** [thecloudnativewebapp/GoCloudNative.Bff#17]
Causes the following exception on the /account/me endpoint

System.FormatException: The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters.
   at System.Convert.FromBase64CharPtr(Char* inputPtr, Int32 inputLength)
   at System.Convert.FromBase64String(String s)
   at GoCloudNative.Bff.Authentication.JwtParser.ParseJwtPayload(String token)
   at GoCloudNative.Bff.Authentication.AccountEndpoints.<>c.<MapAuthenticationEndpoints>b__0_0(HttpContext context, IIdentityProvider identityProvider)
   at lambda_method2(Closure, Object, HttpContext)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)

**Comment by appie2go** [comment]
In some cases the middle section of a jwt is not considered to be valid base64 because it does not contain two = characters in the end. Might, as a result of that, a format exception be thrown, the code retries it with two = characters at the end of the string.

**Comment by appie2go** [comment]
Not fixed...

**Comment by appie2go** [comment]
Try this:

payload = payload.Replace('-', '+').Replace('_', '/');
var base64 = payload.PadRight(payload.Length + (4 - payload.Length % 4) % 4, '=');
var json = Convert.FromBase64String(base64);
